[package]
name = "SetupSmith"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.209"
serde_json = "1.0.128"
serde_yaml = "0.9.34+deprecated"
nix = { version = "0.29.0", features = ["user"] }
whoami = "1.5.2"
duct = "0.13.7"
